name: app_abuelos
description: App accesible y simple para adultos mayores (Ayuda, Pendientes, Calendario)
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true